# Generated by Django 2.2.6 on 2021-04-16 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='текст комментария', verbose_name='текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата комментария', verbose_name='дата комментария')),
                ('author', models.ForeignKey(help_text='пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('post', models.ForeignKey(help_text='публикация', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='публикация')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ('-created',),
            },
        ),
    ]
